name: Semantic Versioning

on:
  push:
    branches:
      - main
      - develop

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic Versioning
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          branch_prefixes: '{"main":"", "develop":"pre"}'
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "src/my-service"
          namespace: my-service
          bump_each_commit: true
          bump_each_commit_patch_pattern: ""
          search_commit_body: false
          user_format_type: "csv"
          enable_prerelease_mode: true
          debug: false
          version_from_branch: false

      - name: Create and Push Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.semver.outputs.version }} -m "Generated tag from GitHub Actions"
          git push origin ${{ steps.semver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
